### ISSUE TITLE
The feature visualization method

### ISSUE THREAD

**Issue by TangYJ1229** [caicch/ICT-Net#2]
The work was so interesting and it was attractive to me. 
The feature visualization results in your paper particularly highlight the superiority of your method such as: Figure 5. 
However, I could not find the code for this feature visualization in the GitHub repository you have shared. 
Could you kindly provide the code for this part?
Email：tangyingjie98@foxmail.com

**Comment by caicch** [comment]
> The work was so interesting and it was attractive to me. The feature visualization results in your paper particularly highlight the superiority of your method such as: Figure 5. However, I could not find the code for this feature visualization in the GitHub repository you have shared. Could you kindly provide the code for this part? Email：[tangyingjie98@foxmail.com](mailto:tangyingjie98@foxmail.com)

Hi, I have uploaded the file as https://github.com/caicch/ICT-Net/blob/main/caption_attn.py; you can modify line 233 for encoder visualization and 275 for decoder.

**Comment by TangYJ1229** [comment]
Thanks a lot!!!!
